### PR TITLE
Optimization of massive loading of tickets #69

### LINKED ISSUE #69: Optimization of massive loading of tickets
The first synchronization of loading tickets, when there are a lot of tickets,
caused the application to stop responding.

### PR DESCRIPTION
**Pull request by githubsrki**
### Closes Issues:
Closes #69 

### Description:
Loading tickets page by page. The page limit is 10 tickets per page

### New packages:
 * No change

### CODE REVIEW

**Comment by Krakaw** [comment]
@githubsrki is this a work in progress or can I merge?

**Comment by githubsrki** [comment]
> @githubsrki is this a work in progress or can I merge?

In this last commit, I did loading ticket page by page from the remote server.
Still testing local pagination, because of the huge amount of data, user experience is not perfect.
Currently implementing endless scrolling or infinite scrolling in the RecyclerView. It is not trivial due to filtering.

**Comment by Krakaw** [comment]
I'm struggling to get it to run without crashing in the emulator.

**Comment by Krakaw** [comment]
When trying it on a device i get the following error:
```
2019-06-13 14:41:25.730 22700-22713/com.bigneon.doorperson I/neon.doorperso: The ClassLoaderContext is a special shared library.
2019-06-13 14:41:25.967 22700-22700/com.bigneon.doorperson I/Perf: Connecting to perf service.
2019-06-13 14:41:25.982 22700-22700/com.bigneon.doorperson I/CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization
2019-06-13 14:41:25.989 22700-22700/com.bigneon.doorperson I/ActivityThread: handleStopService: token=android.os.BinderProxy@3a89cf7 not found.
2019-06-13 14:41:25.990 22700-22700/com.bigneon.doorperson D/AndroidRuntime: Shutting down VM
2019-06-13 14:41:25.992 22700-22700/com.bigneon.doorperson E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bigneon.doorperson, PID: 22700
    java.lang.RuntimeException: Unable to stop service com.bigneon.doorperson.service.SyncService@ca84764: java.lang.IllegalArgumentException: Receiver not registered: com.bigneon.doorperson.service.SyncService$syncAllTablesReceiver$1@4bf0dcd
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3852)
        at android.app.ActivityThread.access$1900(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.bigneon.doorperson.service.SyncService$syncAllTablesReceiver$1@4bf0dcd
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1297)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1522)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
        at com.bigneon.doorperson.service.SyncService.onDestroy(SyncService.kt:38)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3832)
        at android.app.ActivityThread.access$1900(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-06-13 14:41:25.998 22700-22717/com.bigneon.doorperson D/OSTracker: OS Event: crash
2019-06-13 14:41:26.005 22700-22700/com.bigneon.doorperson I/Process: Sending signal. PID: 22700 SIG: 9
```

**Comment by Krakaw** [comment]
These features are being worked on in another branch.

**Pull request closed without merging**
