### PR TITLE
A warning should be shown if a guest checked in while offline using a…

### LINKED ISSUE #21: A warning should be shown if a guest checked in while offline using a duplicate ticket
### Process

- Load an event guest list
- Find a ticket by its ID on the app and in the [box office](https://beta.bigneon.com/box-office/guests)
- Put the phone in flight mode
- Redeem the ticket in the box office on the web
- Redeem the ticket on the app while it is in flight mode.
- Turn off flight mode in the app.

### What should happen

- When the app comes online it attempts to redeem the ticket and it gets a 409 as seen below.
image
- This should be displayed to the doorperson as well as when the ticket was actually redeemed.

### What currently happens

- The 409 is ignored and the latest live data is updated so the doorperson does not know that this is a duplicate scan.

http://cl.ly/29addeedb016

### PR DESCRIPTION
**Pull request by githubsrki**
… duplicate ticket

### Closes Issues:
Closes #21

### Description:
A warning should be shown if a guest checked in while offline using a duplicate ticket.
When synchronization discovers the duplicate ticket checking it shows the message to the user

### New packages:
 * No change

### CODE REVIEW

**Comment by Krakaw** [comment]
I can't compile the app
image

**Comment by Krakaw** [comment]
Just use the ticket id eg: `#13fcb0fc` instead of the whole id.
Also show the name of the person that the ticket belongs to.
image

**Comment by Krakaw** [comment]
The tickets are reporting that they are duplicate when they are not?
http://cl.ly/c2d202cb17ee

**Comment by githubsrki** [comment]
Related to
https://github.com/big-neon/bn-android-doorperson/pull/44

**Pull request closed without merging**
